branch-defaults:
  development:
    environment: null
    group_suffix: null
  master:
    environment: portfolio-dev
    group_suffix: null
global:
  application_name: portfolio
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: tim
  repository: null
  sc: git
  workspace_type: Application
