branch-defaults:
  development:
    environment: Dev-env
    group_suffix: null
  master:
    environment: Dev-env
    group_suffix: null
environment-defaults:
  Dev-env:
    branch: null
    repository: null
global:
  application_name: WebDev-Portfolio
  # branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: tim
  repository: null
  sc: git
  workspace_type: Application
